url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: TableTalk.Rocks
email: mail@jishengtan.me
description: "In TableTalk, we not just talk, we build wonders."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Tan Ji Sheng
  pic: 1
  position: Tech Wizard at <a href="qtixapp.com">Asterisque Technology Malaysia Sdn. Bhd.</a>
  social:
    - title: twitter
      url: https://twitter.com/jsheng0811
    - title: facebook
      url: https://www.facebook.com/JshengTan
    - title: website
      url: http://www.jishengtan.me

- name: Hanif Marzuki
  pic: 2
  position: Rain Maker at <a href="qtixapp.com">Asterisque Technology Malaysia Sdn. Bhd.</a> 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Random Guy
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Multimedia University (Cyberjaya)
  - line: Jalan Multimedia
  - line: 63000 Cyberjaya
  - line: Selangor, Malaysia

# Build settings
markdown: kramdown
permalink: pretty