url: http://tabletalk.rocks
baseurl: ""

# Site settings
title: TableTalk.Rocks
email: mail@jishengtan.me
description: "TableTalk, Start Fast, Succeed Faster."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FF3300
  secondary: FF0019  
  secondary-dark: 333

# Team names, titles and social links

people:
- name: Alysia Goh
  pic: 3
  position: President at TableTalk<br>Co-Founder at TableTalk
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- name: Tan Ji Sheng
  pic: 1
  position: Co-Founder at TableTalk<br>Tech Wizard at <a href="http://www.qtixapp.com">Asterisque Technology Malaysia Sdn. Bhd.</a>
  social:
    - title: facebook
      url: https://www.facebook.com/JshengTan
    - title: linkedin
      url: https://my.linkedin.com/in/jishengtan
    - title: globe
      url: http://www.jishengtan.me

- name: Hanif Marzuki
  pic: 2
  position: Co-Founder at TableTalk<br>Rain Maker at <a href="qtixapp.com">Asterisque Technology Malaysia Sdn. Bhd.</a> 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Gary Maurice
  pic: 4
  position: Co-Founder at TableTalk<br>Co-Founder at <a href="hotmakan.com.my">Hotmakan.com.my</a>
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

#End of co-founder
- name: Charmaine Chia
  pic: 5
  position: Treasurer at TableTalk
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
    - title: linkedin
      url: #

- name: Raja Durai
  pic: 6
  position:  Logistic and Special Task Manager at TableTalk
  social:
    - title: twitter
      url: https://twitter.com/draj_94
    - title: facebook
      url: https://www.facebook.com/raja.durai.587
    - title: linkedin
      url: https://www.linkedin.com/pub/raja-durai/b1/41a/159
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Multimedia University (Cyberjaya)
  - line: Jalan Multimedia
  - line: 63000 Cyberjaya
  - line: Selangor, Malaysia

# Build settings
markdown: kramdown
permalink: pretty